/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as KnowledgeHubRouteImport } from './routes/knowledge-hub'
import { Route as DigitalSolutionsRouteImport } from './routes/digital-solutions'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClientPortalRouteImport } from './routes/client-portal'
import { Route as BusinessServicesRouteImport } from './routes/business-services'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AuthenticatedMyLearningRouteImport } from './routes/_authenticated/my-learning'
import { Route as AuthenticatedLearnCourseIdRouteImport } from './routes/_authenticated/learn.$courseId'
import { Route as AuthenticatedAdminCoursesRouteImport } from './routes/_authenticated/admin.courses'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeHubRoute = KnowledgeHubRouteImport.update({
  id: '/knowledge-hub',
  path: '/knowledge-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalSolutionsRoute = DigitalSolutionsRouteImport.update({
  id: '/digital-solutions',
  path: '/digital-solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientPortalRoute = ClientPortalRouteImport.update({
  id: '/client-portal',
  path: '/client-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessServicesRoute = BusinessServicesRouteImport.update({
  id: '/business-services',
  path: '/business-services',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyLearningRoute = AuthenticatedMyLearningRouteImport.update({
  id: '/my-learning',
  path: '/my-learning',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearnCourseIdRoute =
  AuthenticatedLearnCourseIdRouteImport.update({
    id: '/learn/$courseId',
    path: '/learn/$courseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCoursesRoute =
  AuthenticatedAdminCoursesRouteImport.update({
    id: '/admin/courses',
    path: '/admin/courses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/auth': typeof AuthRoute
  '/business-services': typeof BusinessServicesRoute
  '/client-portal': typeof ClientPortalRoute
  '/contact': typeof ContactRoute
  '/digital-solutions': typeof DigitalSolutionsRoute
  '/knowledge-hub': typeof KnowledgeHubRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/my-learning': typeof AuthenticatedMyLearningRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/learn/$courseId': typeof AuthenticatedLearnCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/auth': typeof AuthRoute
  '/business-services': typeof BusinessServicesRoute
  '/client-portal': typeof ClientPortalRoute
  '/contact': typeof ContactRoute
  '/digital-solutions': typeof DigitalSolutionsRoute
  '/knowledge-hub': typeof KnowledgeHubRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/my-learning': typeof AuthenticatedMyLearningRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/learn/$courseId': typeof AuthenticatedLearnCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRoute
  '/auth': typeof AuthRoute
  '/business-services': typeof BusinessServicesRoute
  '/client-portal': typeof ClientPortalRoute
  '/contact': typeof ContactRoute
  '/digital-solutions': typeof DigitalSolutionsRoute
  '/knowledge-hub': typeof KnowledgeHubRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/my-learning': typeof AuthenticatedMyLearningRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/_authenticated/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/_authenticated/learn/$courseId': typeof AuthenticatedLearnCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academy'
    | '/auth'
    | '/business-services'
    | '/client-portal'
    | '/contact'
    | '/digital-solutions'
    | '/knowledge-hub'
    | '/sitemap.xml'
    | '/my-learning'
    | '/portal'
    | '/admin/courses'
    | '/learn/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academy'
    | '/auth'
    | '/business-services'
    | '/client-portal'
    | '/contact'
    | '/digital-solutions'
    | '/knowledge-hub'
    | '/sitemap.xml'
    | '/my-learning'
    | '/portal'
    | '/admin/courses'
    | '/learn/$courseId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/academy'
    | '/auth'
    | '/business-services'
    | '/client-portal'
    | '/contact'
    | '/digital-solutions'
    | '/knowledge-hub'
    | '/sitemap.xml'
    | '/_authenticated/my-learning'
    | '/_authenticated/portal'
    | '/_authenticated/admin/courses'
    | '/_authenticated/learn/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AcademyRoute: typeof AcademyRoute
  AuthRoute: typeof AuthRoute
  BusinessServicesRoute: typeof BusinessServicesRoute
  ClientPortalRoute: typeof ClientPortalRoute
  ContactRoute: typeof ContactRoute
  DigitalSolutionsRoute: typeof DigitalSolutionsRoute
  KnowledgeHubRoute: typeof KnowledgeHubRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-hub': {
      id: '/knowledge-hub'
      path: '/knowledge-hub'
      fullPath: '/knowledge-hub'
      preLoaderRoute: typeof KnowledgeHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-solutions': {
      id: '/digital-solutions'
      path: '/digital-solutions'
      fullPath: '/digital-solutions'
      preLoaderRoute: typeof DigitalSolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-portal': {
      id: '/client-portal'
      path: '/client-portal'
      fullPath: '/client-portal'
      preLoaderRoute: typeof ClientPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-services': {
      id: '/business-services'
      path: '/business-services'
      fullPath: '/business-services'
      preLoaderRoute: typeof BusinessServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-learning': {
      id: '/_authenticated/my-learning'
      path: '/my-learning'
      fullPath: '/my-learning'
      preLoaderRoute: typeof AuthenticatedMyLearningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learn/$courseId': {
      id: '/_authenticated/learn/$courseId'
      path: '/learn/$courseId'
      fullPath: '/learn/$courseId'
      preLoaderRoute: typeof AuthenticatedLearnCourseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/courses': {
      id: '/_authenticated/admin/courses'
      path: '/admin/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMyLearningRoute: typeof AuthenticatedMyLearningRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
  AuthenticatedAdminCoursesRoute: typeof AuthenticatedAdminCoursesRoute
  AuthenticatedLearnCourseIdRoute: typeof AuthenticatedLearnCourseIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMyLearningRoute: AuthenticatedMyLearningRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
  AuthenticatedAdminCoursesRoute: AuthenticatedAdminCoursesRoute,
  AuthenticatedLearnCourseIdRoute: AuthenticatedLearnCourseIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AcademyRoute: AcademyRoute,
  AuthRoute: AuthRoute,
  BusinessServicesRoute: BusinessServicesRoute,
  ClientPortalRoute: ClientPortalRoute,
  ContactRoute: ContactRoute,
  DigitalSolutionsRoute: DigitalSolutionsRoute,
  KnowledgeHubRoute: KnowledgeHubRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
